//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DipTradeProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistChangePrice
    {
        public int id_h_chrg { get; set; }
        public int id_tovar { get; set; }
        public System.DateTime date_change { get; set; }
        public double old_price { get; set; }
        public double new_price { get; set; }
    
        public virtual Tovar Tovar { get; set; }
    }
}
