//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DipTradeProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hist_Postavka
    {
        public int id_hpost { get; set; }
        public int id_tovar { get; set; }
        public int id_postav { get; set; }
        public double kolvo { get; set; }
        public double price { get; set; }
        public string trader { get; set; }
        public string postav { get; set; }
    
        public virtual Postavshik Postavshik { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
