//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DipTradeProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodazh
    {
        public int rowid { get; set; }
        public int id_tovar { get; set; }
        public System.DateTime date_prod { get; set; }
        public double kolvo { get; set; }
        public double price { get; set; }
        public string trader { get; set; }
    
        public virtual Tovar Tovar { get; set; }
    }
}
